const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '../src/locales');

// We will load English data to use as the base for keys we don't translate fully.
const enJsonPath = path.join(localesDir, 'en.json');
const enData = JSON.parse(fs.readFileSync(enJsonPath, 'utf8'));

// Provide real translations for the sidebar and nav for the 6 languages
const actualTranslations = {
  hi: {
    nav: { dashboard: "डैशबोर्ड", applications: "आवेदन", consent: "सहमति प्रबंधक", language: "भाषा" },
    sidebar: { citizenPortal: "नागरिक पोर्टल", myDashboard: "मेरा डैशबोर्ड", applyService: "सेवा के लिए आवेदन करें", consentManager: "सहमति प्रबंधक", trackApplications: "आवेदन ट्रैक करें", officerPortals: "अधिकारी पोर्टल", revenueDept: "राजस्व विभाग", welfareDept: "कल्याण विभाग", interoperability: "पारस्परिकता", middlewareHub: "मिडलवेयर हब", consolidatedView: "समेकित दृश्य", mdmRegistry: "एमडीएम रजिस्ट्री", monitoring: "निगरानी", systemMonitor: "सिस्टम मॉनिटर", adminPanel: "एडमिन पैनल", apiDocs: "एपीआई दस्तावेज़", logout: "लॉग आउट" },
    dashboard: { header: "नागरिक डैशबोर्ड", welcome: "वापसी पर स्वागत है", applyScheme: "नई योजना के लिए आवेदन करें", consentReq: "डिजिटल सहमति आवश्यक", grantConsent: "अभी सहमति दें", submittedApps: "जमा किए गए आवेदन", verifiedIncomes: "सत्यापित आय", eligibleSchemes: "पात्र योजनाएं", consentStatus: "सहमति की स्थिति", availableSchemes: "उपलब्ध सरकारी कल्याण योजनाएं", apply: "आवेदन करें", myApps: "मेरे आवेदन और स्थिति ट्रैकिंग", viewTimeline: "विस्तृत ट्रैकिंग टाइमलाइन देखें" },
    revenue: { title: "राजस्व विभाग पोर्टल (विरासत प्रणाली)", subtitle: "आधिकारिक भूमि और कर राजस्व निदेशालय • स्वतंत्र विरासत XML डेटाबेस", gatewayActive: "XML गेटवे सक्रिय", idFormat: "राजस्व आईडी प्रारूप", idSubtitle: "स्वतंत्र राजस्व नेमस्पेस", protocol: "प्रतिक्रिया प्रोटोकॉल", protocolSubtitle: "विरासत डेटा विनिमय", health: "सेवा स्वास्थ्य", healthSubtitle: "राजस्व प्रेषण इंजन" },
    welfare: { title: "समाज कल्याण विभाग पोर्टल", subtitle: "आधिकारिक लाभार्थी प्रशासन और प्रत्यक्ष लाभ हस्तांतरण (DBT) पोर्टल", addScheme: "नई कल्याण योजना जोड़ें", totalApps: "कुल आवेदन", totalAppsSub: "योजनाओं में प्राप्त", verifiedIncomes: "सत्यापित आय", verifiedIncomesSub: "मिडलवेयर XML पार्सर के माध्यम से", disbursed: "वितरित लाभ", disbursedSub: "प्रत्यक्ष लाभ हस्तांतरण पूर्ण" },
    admin: { title: "सिस्टम एडमिन और पारस्परिकता निगरानी", subtitle: "API गेटवे विलंबता, क्रॉस-विभाग ऑडिट ट्रेल्स और पात्रता नियमों की वास्तविक समय की निगरानी।", tabMetrics: "सिस्टम मेट्रिक्स", tabAudits: "ऑडिट लॉग", tabRules: "नियम इंजन", metricApps: "कुल आवेदन", metricAppsSub: "मिडलवेयर द्वारा संसाधित", metricVerified: "सत्यापित आवेदन", metricVerifiedSub: "राजस्व XML पार्स और मान्य", metricEligible: "पात्र आवेदन", metricEligibleSub: "पात्रता नियम पारित", metricTime: "औसत प्रसंस्करण समय", metricTimeSub: "एंड-टू-एंड API पाइपलाइन विलंबता" },
    hub: { title: "GovConnect मिडलवेयर हब", subtitle: "केंद्रीय डेटा एक्सचेंज नोड", engineActive: "सिंटैक्टिक इंजन सक्रिय" },
    topology: { title: "क्रॉस-डिपार्टमेंटल डेटा एक्सचेंज नेटवर्क टोपोलॉजी", welfareTitle: "कल्याण विभाग पोर्टल", welfareType: "JSON / REST", welfareDesc: "कल्याण आईडी (CIT-1001) का उपयोग करके योजना अनुरोध सबमिट करता है।", middlewareTitle: "GovConnect मिडलवेयर", middlewareType: "कोर गेटवे", middlewareDesc: "JWT ऑथ, आईडी रिज़ॉल्यूशन और डेटा क्वालिटी को संभालता है।", revenueTitle: "राजस्व विभाग API", revenueType: "XML / REST", revenueDesc: "राजस्व आईडी का उपयोग करके भूमि और आय रिकॉर्ड क्वेरी करता है।" }
  },
  ta: {
    nav: { dashboard: "முகப்பு", applications: "விண்ணப்பங்கள்", consent: "ஒப்புதல் மேலாளர்", language: "மொழி" },
    sidebar: { citizenPortal: "குடிமக்கள் தளம்", myDashboard: "என் முகப்பு", applyService: "சேவைக்கு விண்ணப்பிக்கவும்", consentManager: "ஒப்புதல் மேலாளர்", trackApplications: "விண்ணப்பங்களை கண்காணிக்கவும்", officerPortals: "அதிகாரி தளங்கள்", revenueDept: "வருவாய் துறை", welfareDept: "நலன் துறை", interoperability: "இயங்குதன்மை", middlewareHub: "இடைநிலை மையம்", consolidatedView: "ஒருங்கிணைந்த காட்சி", mdmRegistry: "MDM பதிவேடு", monitoring: "கண்காணிப்பு", systemMonitor: "கணினி கண்காணிப்பு", adminPanel: "நிர்வாகி தளம்", apiDocs: "API ஆவணங்கள்", logout: "வெளியேறு" },
    dashboard: { header: "குடிமக்கள் முகப்பு", welcome: "மீண்டும் வருக", applyScheme: "புதிய திட்டத்திற்கு விண்ணப்பிக்கவும்", consentReq: "டிஜிட்டல் ஒப்புதல் தேவை", grantConsent: "இப்போது ஒப்புதல் அளிக்கவும்", submittedApps: "சமர்ப்பிக்கப்பட்ட விண்ணப்பங்கள்", verifiedIncomes: "சரிபார்க்கப்பட்ட வருமானம்", eligibleSchemes: "தகுதியான திட்டங்கள்", consentStatus: "ஒப்புதல் நிலை", availableSchemes: "கிடைக்கும் அரசு நலத் திட்டங்கள்", apply: "விண்ணப்பிக்கவும்", myApps: "என் விண்ணப்பங்கள் மற்றும் நிலை கண்காணிப்பு", viewTimeline: "விரிவான கண்காணிப்பு காலவரிசையை காண்க" },
    revenue: { title: "வருவாய் துறை தளம் (பழைய கணினி)", subtitle: "அதிகாரப்பூர்வ நில மற்றும் வரி வருவாய் இயக்குநரகம் • சுதந்திரமான பழைய XML தரவுத்தளம்", gatewayActive: "XML நுழைவாயில் செயலில்", idFormat: "வருவாய் ID வடிவம்", idSubtitle: "சுதந்திர வருவாய் நேம்ஸ்பேஸ்", protocol: "பதிலளிப்பு நெறிமுறை", protocolSubtitle: "பழைய தரவு பரிமாற்றம்", health: "சேவை சுகாதாரம்", healthSubtitle: "வருவாய் அனுப்பும் இயந்திரம்" },
    welfare: { title: "சமூக நலத்துறை தளம்", subtitle: "அதிகாரப்பூர்வ பயனாளிகள் நிர்வாகம் & நேரடி பயன் மாற்ற (DBT) தளம்", addScheme: "புதிய நலத்திட்டத்தை சேர்க்கவும்", totalApps: "மொத்த விண்ணப்பங்கள்", totalAppsSub: "திட்டங்களில் பெறப்பட்டவை", verifiedIncomes: "சரிபார்க்கப்பட்ட வருமானங்கள்", verifiedIncomesSub: "இடைநிலை XML பார்சர் மூலம் பெறப்பட்டது", disbursed: "வழங்கப்பட்ட நன்மைகள்", disbursedSub: "நேரடி பயன் மாற்றம் முடிந்தது" },
    admin: { title: "கணினி நிர்வாகி & இயங்குதன்மை கண்காணிப்பு", subtitle: "API நுழைவாயில் தாமதம், துறைகளுக்கு இடையிலான தணிக்கை தடங்கள் மற்றும் தகுதி விதிகளின் நிகழ்நேர கண்காணிப்பு.", tabMetrics: "கணினி அளவீடுகள்", tabAudits: "தணிக்கை பதிவுகள்", tabRules: "விதி இயந்திரம்", metricApps: "மொத்த விண்ணப்பங்கள்", metricAppsSub: "இடைநிலையால் கையாளப்பட்டது", metricVerified: "சரிபார்க்கப்பட்ட விண்ணப்பங்கள்", metricVerifiedSub: "வருவாய் XML சரிபார்க்கப்பட்டது", metricEligible: "தகுதியான விண்ணப்பங்கள்", metricEligibleSub: "தகுதி விதிகள் கடந்துவிட்டன", metricTime: "சராசரி செயலாக்க நேரம்", metricTimeSub: "முழு API தாமதம்" },
    hub: { title: "GovConnect இடைநிலை மையம்", subtitle: "மத்திய தரவு பரிமாற்ற முனை", engineActive: "இயந்திரம் செயலில்" },
    topology: { title: "துறைகளுக்கு இடையிலான தரவு பரிமாற்ற நெட்வொர்க்", welfareTitle: "நலத்துறை தளம்", welfareType: "JSON / REST", welfareDesc: "நலன் ஐடியைப் பயன்படுத்தி திட்டக் கோரிக்கைகளைச் சமர்ப்பிக்கிறது.", middlewareTitle: "GovConnect இடைநிலை", middlewareType: "முதன்மை நுழைவாயில்", middlewareDesc: "JWT அங்கீகாரம், ஐடித் தீர்வு மற்றும் தரக் கட்டுப்பாட்டைக் கையாள்கிறது.", revenueTitle: "வருவாய் துறை API", revenueType: "XML / REST", revenueDesc: "வருவாய் ஐடியைப் பயன்படுத்தி தரவைக் கோருகிறது." }
  },
  te: {
    nav: { dashboard: "డాష్‌బోర్డ్", applications: "దరఖాస్తులు", consent: "సమ్మతి నిర్వాహకుడు", language: "భాష" },
    sidebar: { citizenPortal: "పౌర పోర్టల్", myDashboard: "నా డాష్‌బోర్డ్", applyService: "సేవ కోసం దరఖాస్తు చేయండి", consentManager: "సమ్మతి నిర్వాహకుడు", trackApplications: "దరఖాస్తులను ట్రాక్ చేయండి", officerPortals: "అధికారి పోర్టల్స్", revenueDept: "రెవెన్యూ శాఖ", welfareDept: "సంక్షేమ శాఖ", interoperability: "పరస్పర చర్య", middlewareHub: "మిడిల్‌వేర్ హబ్", consolidatedView: "సమీకృత వీక్షణ", mdmRegistry: "MDM రిజిస్ట్రీ", monitoring: "పర్యవేక్షణ", systemMonitor: "సిస్టమ్ మానిటర్", adminPanel: "అడ్మిన్ ప్యానెల్", apiDocs: "API డాక్స్", logout: "లాగ్ అవుట్" },
    dashboard: { header: "పౌర డాష్‌బోర్డ్", welcome: "తిరిగి స్వాగతం", applyScheme: "కొత్త పథకం కోసం దరఖాస్తు చేయండి", consentReq: "డిజిటల్ సమ్మతి అవసరం", grantConsent: "ఇప్పుడే సమ్మతిని మంజూరు చేయండి", submittedApps: "సమర్పించిన దరఖాస్తులు", verifiedIncomes: "ధృవీకరించిన ఆదాయాలు", eligibleSchemes: "అర్హత ఉన్న పథకాలు", consentStatus: "సమ్మతి స్థితి", availableSchemes: "అందుబాటులో ఉన్న ప్రభుత్వ సంక్షేమ పథకాలు", apply: "దరఖాస్తు చేయండి", myApps: "నా దరఖాస్తులు & స్థితి ట్రాకింగ్", viewTimeline: "వివరణాత్మక ట్రాకింగ్ కాలక్రమాన్ని చూడండి" },
    revenue: { title: "రెవెన్యూ డిపార్ట్‌మెంట్ పోర్టల్ (వారసత్వ వ్యవస్థ)", subtitle: "అధికారిక భూమి & పన్ను రాబడి డైరెక్టరేట్ • స్వతంత్ర వారసత్వ XML డేటాబేస్", gatewayActive: "XML గేట్‌వే యాక్టివ్", idFormat: "రెవెన్యూ ID ఫార్మాట్", idSubtitle: "స్వతంత్ర రెవెన్యూ నేమ్‌స్పేస్", protocol: "ప్రతిస్పందన ప్రోటోకాల్", protocolSubtitle: "వారసత్వ డేటా మార్పిడి", health: "సేవా ఆరోగ్యం", healthSubtitle: "రెవెన్యూ డిస్పాచ్ ఇంజిన్" },
    welfare: { title: "సాంఘిక సంక్షేమ శాఖ పోర్టల్", subtitle: "అధికారిక లబ్ధిదారుల పరిపాలన & ప్రత్యక్ష ప్రయోజన బదిలీ (DBT) పోర్టల్", addScheme: "కొత్త సంక్షేమ పథకాన్ని జోడించండి", totalApps: "మొత్తం దరఖాస్తులు", totalAppsSub: "పథకాల్లో స్వీకరించబడింది", verifiedIncomes: "ధృవీకరించబడిన ఆదాయాలు", verifiedIncomesSub: "మిడిల్‌వేర్ XML పార్సర్ ద్వారా", disbursed: "పంపిణీ చేసిన ప్రయోజనాలు", disbursedSub: "ప్రత్యక్ష ప్రయోజన బదిలీ పూర్తయింది" },
    admin: { title: "సిస్టమ్ అడ్మిన్ & ఇంటర్‌ఆపరేబిలిటీ మానిటరింగ్", subtitle: "API గేట్‌వే జాప్యం, క్రాస్-డిపార్ట్‌మెంట్ ఆడిట్ ట్రెయిల్స్ మరియు నిబంధనల నిజ-సమయ పర్యవేక్షణ.", tabMetrics: "సిస్టమ్ మెట్రిక్స్", tabAudits: "ఆడిట్ లాగ్‌లు", tabRules: "నియమాల ఇంజిన్", metricApps: "మొత్తం దరఖాస్తులు", metricAppsSub: "మిడిల్‌వేర్ ద్వారా ప్రాసెస్ చేయబడింది", metricVerified: "ధృవీకరించిన దరఖాస్తులు", metricVerifiedSub: "రెవెన్యూ XML ధృవీకరించబడింది", metricEligible: "అర్హత ఉన్న దరఖాస్తులు", metricEligibleSub: "నిబంధనలు ఆమోదించబడ్డాయి", metricTime: "సగటు ప్రాసెసింగ్ సమయం", metricTimeSub: "API పైప్‌లైన్ జాప్యం" },
    hub: { title: "GovConnect మిడిల్‌వేర్ హబ్", subtitle: "సెంట్రల్ డేటా ఎక్స్ఛేంజ్ నోడ్", engineActive: "ఇంజిన్ యాక్టివ్" },
    topology: { title: "క్రాస్-డిపార్ట్‌మెంటల్ డేటా ఎక్స్ఛేంజ్ నెట్‌వర్క్", welfareTitle: "సంక్షేమ శాఖ పోర్టల్", welfareType: "JSON / REST", welfareDesc: "పథకం అభ్యర్థనలను సమర్పిస్తుంది.", middlewareTitle: "GovConnect మిడిల్‌వేర్", middlewareType: "కోర్ గేట్‌వే", middlewareDesc: "JWT మరియు డేటా క్వాలిటీని నిర్వహిస్తుంది.", revenueTitle: "రెవెన్యూ API", revenueType: "XML / REST", revenueDesc: "ఆదాయ రికార్డులను ప్రశ్నిస్తుంది." }
  },
  mr: {
    nav: { dashboard: "डॅशबोर्ड", applications: "अर्ज", consent: "संमती व्यवस्थापक", language: "भाषा" },
    sidebar: { citizenPortal: "नागरिक पोर्टल", myDashboard: "माझा डॅशबोर्ड", applyService: "सेवेसाठी अर्ज करा", consentManager: "संमती व्यवस्थापक", trackApplications: "अर्जांचा मागोवा घ्या", officerPortals: "अधिकारी पोर्टल", revenueDept: "महसूल विभाग", welfareDept: "कल्याण विभाग", interoperability: "आंतरकार्यक्षमता", middlewareHub: "मिडलवेअर हब", consolidatedView: "एकत्रित दृश्य", mdmRegistry: "एमडीएम नोंदणी", monitoring: "देखरेख", systemMonitor: "सिस्टम मॉनिटर", adminPanel: "अॅडमिन पॅनेल", apiDocs: "एपीआय दस्तऐवज", logout: "लॉग आउट" },
    dashboard: { header: "नागरिक डॅशबोर्ड", welcome: "परत स्वागत आहे", applyScheme: "नवीन योजनेसाठी अर्ज करा", consentReq: "डिजिटल संमती आवश्यक", grantConsent: "आता संमती द्या", submittedApps: "सादर केलेले अर्ज", verifiedIncomes: "सत्यापित उत्पन्न", eligibleSchemes: "पात्र योजना", consentStatus: "संमतीची स्थिती", availableSchemes: "उपलब्ध सरकारी कल्याण योजना", apply: "अर्ज करा", myApps: "माझे अर्ज आणि स्थिती ट्रॅकिंग", viewTimeline: "तपशीलवार ट्रॅकिंग टाइमलाइन पहा" },
    revenue: { title: "महसूल विभाग पोर्टल (वारसा प्रणाली)", subtitle: "अधिकृत जमीन आणि कर महसूल संचालनालय • स्वतंत्र वारसा XML डेटाबेस", gatewayActive: "XML गेटवे सक्रिय", idFormat: "महसूल आयडी स्वरूप", idSubtitle: "स्वतंत्र महसूल नेमस्पेस", protocol: "प्रतिसाद प्रोटोकॉल", protocolSubtitle: "वारसा डेटा एक्सचेंज", health: "सेवा आरोग्य", healthSubtitle: "महसूल प्रेषण इंजिन" },
    welfare: { title: "समाज कल्याण विभाग पोर्टल", subtitle: "अधिकृत लाभार्थी प्रशासन आणि थेट लाभ हस्तांतरण (DBT) पोर्टल", addScheme: "नवीन कल्याण योजना जोडा", totalApps: "एकूण अर्ज", totalAppsSub: "योजनांमध्ये प्राप्त", verifiedIncomes: "सत्यापित उत्पन्न", verifiedIncomesSub: "मिडलवेअर XML पार्सर द्वारे", disbursed: "वितरित लाभ", disbursedSub: "थेट लाभ हस्तांतरण पूर्ण" },
    admin: { title: "सिस्टम अॅडमिन आणि इंटरऑपरेबिलिटी मॉनिटरिंग", subtitle: "API गेटवे विलंब, क्रॉस-डिपार्टमेंट ऑडिट आणि पात्रता नियमांचे रिअल-टाइम मॉनिटरिंग.", tabMetrics: "सिस्टम मेट्रिक्स", tabAudits: "ऑडिट लॉग", tabRules: "नियम इंजिन", metricApps: "एकूण अर्ज", metricAppsSub: "मिडलवेअर द्वारे प्रक्रियाकृत", metricVerified: "सत्यापित अर्ज", metricVerifiedSub: "महसूल XML प्रमाणित", metricEligible: "पात्र अर्ज", metricEligibleSub: "नियम पास झाले", metricTime: "सरासरी वेळ", metricTimeSub: "API पाइपलाइन विलंब" },
    hub: { title: "GovConnect मिडलवेअर हब", subtitle: "मध्यवर्ती डेटा एक्सचेंज नोड", engineActive: "इंजिन सक्रिय" },
    topology: { title: "क्रॉस-डिपार्टमेंटल डेटा एक्सचेंज नेटवर्क", welfareTitle: "कल्याण विभाग पोर्टल", welfareType: "JSON / REST", welfareDesc: "कल्याण आयडी वापरून अर्ज सबमिट करते.", middlewareTitle: "GovConnect मिडलवेअर", middlewareType: "कोअर गेटवे", middlewareDesc: "प्रमाणीकरण आणि डेटा गुणवत्ता हाताळते.", revenueTitle: "महसूल API", revenueType: "XML / REST", revenueDesc: "जमीन आणि उत्पन्न रेकॉर्डची चौकशी करते." }
  },
  ml: {
    nav: { dashboard: "ഡാഷ്ബോർഡ്", applications: "അപേക്ഷകൾ", consent: "സമ്മത മാനേജർ", language: "ഭാഷ" },
    sidebar: { citizenPortal: "പൗര പോർട്ടൽ", myDashboard: "എൻ്റെ ഡാഷ്ബോർഡ്", applyService: "സേവനത്തിനായി അപേക്ഷിക്കുക", consentManager: "സമ്മത മാനേജർ", trackApplications: "അപേക്ഷകൾ ട്രാക്ക് ചെയ്യുക", officerPortals: "ഉദ്യോഗസ്ഥ പോർട്ടലുകൾ", revenueDept: "റവന്യൂ വകുപ്പ്", welfareDept: "ക്ഷേമ വകുപ്പ്", interoperability: "പരസ്പര പ്രവർത്തനക്ഷമത", middlewareHub: "മിഡിൽവെയർ ഹബ്", consolidatedView: "ഏകീകൃത കാഴ്ച", mdmRegistry: "എംഡിഎം രജിസ്ട്രി", monitoring: "നിരീക്ഷണം", systemMonitor: "സിസ്റ്റം മോണിറ്റർ", adminPanel: "അഡ്മിൻ പാനൽ", apiDocs: "API പ്രമാണങ്ങൾ", logout: "ലോഗ് ഔട്ട്" },
    dashboard: { header: "പൗര ഡാഷ്ബോർഡ്", welcome: "തിരികെ സ്വാഗതം", applyScheme: "പുതിയ പദ്ധതിക്കായി അപേക്ഷിക്കുക", consentReq: "ഡിജിറ്റൽ സമ്മതം ആവശ്യമാണ്", grantConsent: "ഇപ്പോൾ സമ്മതം നൽകുക", submittedApps: "സമർപ്പിച്ച അപേക്ഷകൾ", verifiedIncomes: "സ്ഥിരീകരിച്ച വരുമാനം", eligibleSchemes: "യോഗ്യമായ പദ്ധതികൾ", consentStatus: "സമ്മത നില", availableSchemes: "ലഭ്യമായ സർക്കാർ ക്ഷേമ പദ്ധതികൾ", apply: "അപേക്ഷിക്കുക", myApps: "എൻ്റെ അപേക്ഷകളും ട്രാക്കിംഗും", viewTimeline: "വിശദമായ ട്രാക്കിംഗ് സമയരേഖ കാണുക" },
    revenue: { title: "റവന്യൂ ഡിപ്പാർട്ട്മെന്റ് പോർട്ടൽ (പഴയ സിസ്റ്റം)", subtitle: "ഔദ്യോഗിക ഭൂമി & നികുതി റവന്യൂ ഡയറക്ടറേറ്റ് • സ്വതന്ത്ര പഴയ XML ഡാറ്റാബേസ്", gatewayActive: "XML ഗേറ്റ്‌വേ സജീവം", idFormat: "റവന്യൂ ഐഡി ഫോർമാറ്റ്", idSubtitle: "സ്വതന്ത്ര റവന്യൂ നെയിംസ്‌പേസ്", protocol: "പ്രതികരണ പ്രോട്ടോക്കോൾ", protocolSubtitle: "പഴയ ഡാറ്റ കൈമാറ്റം", health: "സേവന ആരോഗ്യം", healthSubtitle: "റവന്യൂ ഡിസ്പാച്ച് എഞ്ചിൻ" },
    welfare: { title: "സാമൂഹിക ക്ഷേമ വകുപ്പ് പോർട്ടൽ", subtitle: "ഔദ്യോഗിക ഗുണഭോക്തൃ ഭരണം & ഡയറക്ട് ബെനഫിറ്റ് ട്രാൻസ്ഫർ (DBT) പോർട്ടൽ", addScheme: "പുതിയ ക്ഷേമ പദ്ധതി ചേർക്കുക", totalApps: "ആകെ അപേക്ഷകൾ", totalAppsSub: "ലഭിച്ചവ", verifiedIncomes: "സ്ഥിരീകരിച്ച വരുമാനം", verifiedIncomesSub: "മിഡിൽവെയർ XML പാർസർ വഴി", disbursed: "വിതരണം ചെയ്ത ആനുകൂല്യങ്ങൾ", disbursedSub: "DBT പൂർത്തിയായി" },
    admin: { title: "സിസ്റ്റം അഡ്മിൻ & ഇന്റർഓപ്പറബിലിറ്റി മോണിറ്ററിംഗ്", subtitle: "API ഗേറ്റ്‌വേ, ഓഡിറ്റ് ലോഗുകൾ എന്നിവയുടെ തത്സമയ നിരീക്ഷണം.", tabMetrics: "സിസ്റ്റം മെട്രിക്സ്", tabAudits: "ഓഡിറ്റ് ലോഗുകൾ", tabRules: "റൂൾസ് എഞ്ചിൻ", metricApps: "ആകെ അപേക്ഷകൾ", metricAppsSub: "പ്രോസസ്സ് ചെയ്തവ", metricVerified: "സ്ഥിരീകരിച്ചവ", metricVerifiedSub: "റവന്യൂ XML അംഗീകരിച്ചു", metricEligible: "യോഗ്യമായവ", metricEligibleSub: "നിയമങ്ങൾ പാസായി", metricTime: "ശരാശരി സമയം", metricTimeSub: "API ലേറ്റൻസി" },
    hub: { title: "GovConnect മിഡിൽവെയർ ഹബ്", subtitle: "സെൻട്രൽ ഡാറ്റ എക്സ്ചേഞ്ച് നോഡ്", engineActive: "എഞ്ചിൻ സജീവം" },
    topology: { title: "ക്രോസ്-ഡിപ്പാർട്ട്മെന്റൽ ഡാറ്റ നെറ്റ്‌വർക്ക്", welfareTitle: "ക്ഷേമ പോർട്ടൽ", welfareType: "JSON / REST", welfareDesc: "അപേക്ഷകൾ സമർപ്പിക്കുന്നു.", middlewareTitle: "GovConnect മിഡിൽവെയർ", middlewareType: "കോർ ഗേറ്റ്‌വേ", middlewareDesc: "സെക്യൂരിറ്റി കൈകാര്യം ചെയ്യുന്നു.", revenueTitle: "റവന്യൂ API", revenueType: "XML / REST", revenueDesc: "ഡാറ്റ നൽകുന്നു." }
  },
  kn: {
    nav: { dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", applications: "ಅರ್ಜಿಗಳು", consent: "ಸಮ್ಮತಿ ನಿರ್ವಾಹಕ", language: "ಭಾಷೆ" },
    sidebar: { citizenPortal: "ನಾಗರಿಕ ಪೋರ್ಟಲ್", myDashboard: "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", applyService: "ಸೇವೆಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ", consentManager: "ಸಮ್ಮತಿ ನಿರ್ವಾಹಕ", trackApplications: "ಅರ್ಜಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", officerPortals: "ಅಧಿಕಾರಿ ಪೋರ್ಟಲ್‌ಗಳು", revenueDept: "ಕಂದಾಯ ಇಲಾಖೆ", welfareDept: "ಕಲ್ಯಾಣ ಇಲಾಖೆ", interoperability: "ಪರಸ್ಪರ ಕಾರ್ಯಸಾಧ್ಯತೆ", middlewareHub: "ಮಿಡಲ್ವೇರ್ ಹಬ್", consolidatedView: "ಏಕೀಕೃತ ನೋಟ", mdmRegistry: "MDM ನೋಂದಣಿ", monitoring: "ಮೇಲ್ವಿಚಾರಣೆ", systemMonitor: "ಸಿಸ್ಟಮ್ ಮಾನಿಟರ್", adminPanel: "ನಿರ್ವಾಹಕ ಫಲಕ", apiDocs: "API ದಾಖಲೆಗಳು", logout: "ಲಾಗ್ ಔಟ್" },
    dashboard: { header: "ನಾಗರಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", welcome: "ಮತ್ತೆ ಸ್ವಾಗತ", applyScheme: "ಹೊಸ ಯೋಜನೆಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ", consentReq: "ಡಿಜಿಟಲ್ ಸಮ್ಮತಿ ಅಗತ್ಯವಿದೆ", grantConsent: "ಈಗ ಸಮ್ಮತಿ ನೀಡಿ", submittedApps: "ಸಲ್ಲಿಸಿದ ಅರ್ಜಿಗಳು", verifiedIncomes: "ಪರಿಶೀಲಿಸಿದ ಆದಾಯಗಳು", eligibleSchemes: "ಅರ್ಹ ಯೋಜನೆಗಳು", consentStatus: "ಸಮ್ಮತಿ ಸ್ಥಿತಿ", availableSchemes: "ಲಭ್ಯವಿರುವ ಸರ್ಕಾರಿ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳು", apply: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ", myApps: "ನನ್ನ ಅರ್ಜಿಗಳು ಮತ್ತು ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕಿಂಗ್", viewTimeline: "ವಿವರವಾದ ಟ್ರ್ಯಾಕಿಂಗ್ ಟೈಮ್‌ಲೈನ್ ವೀಕ್ಷಿಸಿ" },
    revenue: { title: "ಕಂದಾಯ ಇಲಾಖೆ ಪೋರ್ಟಲ್ (ಹಳೆಯ ವ್ಯವಸ್ಥೆ)", subtitle: "ಅಧಿಕೃತ ಭೂಮಿ ಮತ್ತು ತೆರಿಗೆ ಕಂದಾಯ ನಿರ್ದೇಶನಾಲಯ • ಸ್ವತಂತ್ರ ಹಳೆಯ XML ಡೇಟಾಬೇಸ್", gatewayActive: "XML ಗೇಟ್‌ವೇ ಸಕ್ರಿಯ", idFormat: "ಕಂದಾಯ ಐಡಿ ಸ್ವರೂಪ", idSubtitle: "ಸ್ವತಂತ್ರ ಕಂದಾಯ ನೇಮ್‌ಸ್ಪೇಸ್", protocol: "ಪ್ರತಿಕ್ರಿಯೆ ಪ್ರೋಟೋಕಾಲ್", protocolSubtitle: "ಹಳೆಯ ಡೇಟಾ ವಿನಿಮಯ", health: "ಸೇವಾ ಆರೋಗ್ಯ", healthSubtitle: "ಕಂದಾಯ ರವಾನೆ ಎಂಜಿನ್" },
    welfare: { title: "ಸಮಾಜ ಕಲ್ಯಾಣ ಇಲಾಖೆ ಪೋರ್ಟಲ್", subtitle: "ಅಧಿಕೃತ ಫಲಾನುಭವಿ ಆಡಳಿತ ಮತ್ತು ನೇರ ಲಾಭ ವರ್ಗಾವಣೆ (DBT) ಪೋರ್ಟಲ್", addScheme: "ಹೊಸ ಕಲ್ಯಾಣ ಯೋಜನೆ ಸೇರಿಸಿ", totalApps: "ಒಟ್ಟು ಅರ್ಜಿಗಳು", totalAppsSub: "ಯೋಜನೆಗಳಲ್ಲಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ", verifiedIncomes: "ಪರಿಶೀಲಿಸಿದ ಆದಾಯಗಳು", verifiedIncomesSub: "ಮಿಡಲ್ವೇರ್ XML ಪಾರ್ಸರ್ ಮೂಲಕ", disbursed: "ವಿತರಿಸಿದ ಲಾಭಗಳು", disbursedSub: "ನೇರ ಲಾಭ ವರ್ಗಾವಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ" },
    admin: { title: "ಸಿಸ್ಟಮ್ ಅಡ್ಮಿನ್ ಮತ್ತು ಇಂಟರ್‌ಆಪರೇಬಿಲಿಟಿ ಮಾನಿಟರಿಂಗ್", subtitle: "API ಗೇಟ್‌ವೇ ಲೇಟೆನ್ಸಿ ಮತ್ತು ಆಡಿಟ್ ಲಾಗ್‌ಗಳ ನೈಜ-ಸಮಯದ ಮೇಲ್ವಿಚಾರಣೆ.", tabMetrics: "ಸಿಸ್ಟಮ್ ಮೆಟ್ರಿಕ್ಸ್", tabAudits: "ಆಡಿಟ್ ಲಾಗ್‌ಗಳು", tabRules: "ನಿಯಮಗಳ ಎಂಜಿನ್", metricApps: "ಒಟ್ಟು ಅರ್ಜಿಗಳು", metricAppsSub: "ಮಿಡಲ್ವೇರ್ ಮೂಲಕ ಸಂಸ್ಕರಿಸಲಾಗಿದೆ", metricVerified: "ಪರಿಶೀಲಿಸಿದ ಅರ್ಜಿಗಳು", metricVerifiedSub: "ಕಂದಾಯ XML ಪರಿಶೀಲಿಸಲಾಗಿದೆ", metricEligible: "ಅರ್ಹ ಅರ್ಜಿಗಳು", metricEligibleSub: "ನಿಯಮಗಳು ಪಾಸ್ ಆಗಿವೆ", metricTime: "ಸರಾಸರಿ ಸಮಯ", metricTimeSub: "API ಲೇಟೆನ್ಸಿ" },
    hub: { title: "GovConnect ಮಿಡಲ್ವೇರ್ ಹಬ್", subtitle: "ಕೇಂದ್ರ ಡೇಟಾ ವಿನಿಮಯ ನೋಡ್", engineActive: "ಎಂಜಿನ್ ಸಕ್ರಿಯ" },
    topology: { title: "ಅಡ್ಡ-ಇಲಾಖಾ ಡೇಟಾ ನೆಟ್‌ವರ್ಕ್", welfareTitle: "ಕಲ್ಯಾಣ ಪೋರ್ಟಲ್", welfareType: "JSON / REST", welfareDesc: "ಅರ್ಜಿಗಳನ್ನು ಸಲ್ಲಿಸುತ್ತದೆ.", middlewareTitle: "GovConnect ಮಿಡಲ್ವೇರ್", middlewareType: "ಕೋರ್ ಗೇಟ್‌ವೇ", middlewareDesc: "ಭದ್ರತೆಯನ್ನು ನಿರ್ವಹಿಸುತ್ತದೆ.", revenueTitle: "ಕಂದಾಯ API", revenueType: "XML / REST", revenueDesc: "ಡೇಟಾವನ್ನು ಒದಗಿಸುತ್ತದೆ." }
  }
};

for (const [lang, translations] of Object.entries(actualTranslations)) {
  const langPath = path.join(localesDir, `${lang}.json`);
  
  // Start with English base so missing keys don't break the app
  // and we don't use prefixes anymore.
  let fullData = JSON.parse(JSON.stringify(enData));
  
  // Merge in our real translations
  fullData.nav = { ...fullData.nav, ...translations.nav };
  fullData.sidebar = { ...fullData.sidebar, ...translations.sidebar };
  fullData.dashboard = { ...fullData.dashboard, ...translations.dashboard };
  fullData.revenue = { ...fullData.revenue, ...translations.revenue };
  fullData.welfare = { ...fullData.welfare, ...translations.welfare };
  fullData.admin = { ...fullData.admin, ...translations.admin };
  fullData.hub = { ...fullData.hub, ...translations.hub };
  fullData.topology = { ...fullData.topology, ...translations.topology };
  
  // Just translate 'Revenue Dept' in departments as a bonus
  fullData.departments = { 
    ...fullData.departments, 
    revenue: translations.sidebar.revenueDept 
  };
  
  fs.writeFileSync(langPath, JSON.stringify(fullData, null, 2));
  console.log(`Generated real translations for ${lang}`);
}
